/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter (ST) for emWin V5.32.                      *
*        Compiled Oct  8 2015, 11:58:22                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: lch                                                   *
* Dimensions:  64 * 64                                               *
* NumColors:   2                                                     *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmlch;

#if 0


/*********************************************************************
*
*  This palette is included for reference only
*  As it is saved as device dependent bitmap without color info.
*  Please note that this bitmap requires the physical palette to be
*  identical to the palette of the display.
*  If this does not work out, please convert your bitmap into a DIB 
*/
/*********************************************************************
*
*       Palette
*
*  Description
*    The following are the entries of the palette table.
*    The entries are stored as a 32-bit values of which 24 bits are
*    actually used according to the following bit mask: 0xBBGGRR
*
*    The lower   8 bits represent the Red   component.
*    The middle  8 bits represent the Green component.
*    The highest 8 bits represent the Blue  component.
*/
static GUI_CONST_STORAGE GUI_COLOR _Colorslch[] = {
  0xFFFFFF, 0x000000
};

#endif

static GUI_CONST_STORAGE GUI_LOGPALETTE _Pallch = {
  2,  // Number of entries
  0,  // No transparency
  NULL
};

static GUI_CONST_STORAGE unsigned char _aclch[] = {
  XXXXXXXX, XXXXXXXX, XXXXXX__, _XX_____, _XXX__XX, _XXXXXXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XX______, ________, ______X_, ______XX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, ________, ________, ________, _____X__, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXX__, ________, ________, ________, ________, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXX_X_, ________, ________, ________, ________, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXX____, ________, ________, ________, ________, __XXXXXX, XXXXXXXX,
  XXXXXXXX, XXX__X__, ________, ________, ________, ________, ___XXXXX, XXXXXXXX,
  XXXXXXXX, X__XX___, ________, ________, ________, ________, ___XXXXX, XXXXXXXX,
  XXXXXXXX, XXXX____, ________, ________, ________, ________, ____XXXX, XXXXXXXX,
  XXXXXXXX, XX______, ________, ________, ________, ________, _____XXX, XXXXXXXX,
  XXXXXXXX, XXXX____, ________, ________, ________, ________, _____XXX, XXXXXXXX,
  XXXXXXXX, XXX_____, ________, ________, ________, ________, ______XX, XXXXXXXX,
  XXXXXXXX, X_______, ________, ________, ________, ________, _______X, XXXXXXXX,
  XXXXXXXX, ________, ________, ________, ________, ________, _____XXX, XXXXXXXX,
  XXXXXXX_, ________, ________, ________, ________, ________, _______X, XXXXXXXX,
  XXXXXXX_, ________, ________, ________, ________, ________, ________, XXXXXXXX,
  XXXXXXXX, ________, ________, ________, ________, ________, _______X, XXXXXXXX,
  XXXXXXXX, ________, ________, __X_____, ________, ________, _______X, XXXXXXXX,
  XXXXXXX_, ________, ________, ___X____, ________, ________, _______X, XXXXXXXX,
  XXXXXXX_, ________, ________, ____X___, ________, ________, _______X, XXXXXXXX,
  XXXXXXX_, ________, ________, ________, ________, ________, _______X, XXXXXXXX,
  XXXXXXX_, _X______, ________, ____X___, ________, ________, _______X, XXXXXXXX,
  XXXXXXXX, X_______, ___XX___, _XXXX___, ________, ________, _____X_X, XXXXXXXX,
  XXXXXXXX, X_______, ____X___, XXXXX___, ________, ________, ______XX, XXXXXXXX,
  XXXXXXXX, X_______, _X_XX__X, XXXXXXXX, X____XXX, ________, _____XXX, XXXXXXXX,
  XXXXXXXX, X_______, __XXXXXX, XXXXXXXX, XXXXXXXX, ________, ____XXXX, XXXXXXXX,
  XXXXXXXX, X_______, XX______, XXXXXXXX, XXXXX___, _______X, X__XXXXX, XXXXXXXX,
  XXXXXXXX, X_______, X_______, ___XXXXX, XXX_____, ________, ___XXXXX, XXXXXXXX,
  XXXXXXXX, _______X, XXXXXXXX, XX__XXXX, XX__XXXX, XXXXX_XX, ____XXXX, XXXXXXXX,
  XXXXXXXX, XXX__XXX, XXXXXXXX, XXX__XXX, X__XXXXX, XXXXXXXX, X___XXXX, XXXXXXXX,
  XXXXXXXX, XXX__XXX, XXXXXXXX, __XX_X_X, X_XXXXXX, _XXXXXXX, _X__XXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, _______X, X_XXXXXX, _XXXXX__, ____XXXX, _X_X_XXX, XXXXXXXX,
  XXXXXXXX, XX_XXXXX, ________, XXXXXXXX, _XXXX___, ____XX_X, _X____XX, XXXXXXXX,
  XXXXXXXX, XX_XXXXX, X______X, XXXXXXXX, _XXXX___, ____XX__, XX____XX, XXXXXXXX,
  XXXXXXXX, XX_XXXXX, XXXXXXXX, XXXXXXXX, __XXXXXX, XXXXX_X_, XX___XXX, XXXXXXXX,
  XXXXXXXX, XX_X_XXX, XXXXXXXX, XXXXXXXX, __XXXXXX, XXXXXXX_, XX___XXX, XXXXXXXX,
  XXXXXXXX, XX___XXX, XXXXXXXX, XXXXXXX_, _XXXXXXX, XXXX_XX_, X____XXX, XXXXXXXX,
  XXXXXXXX, XXX__XXX, XXXXXXXX, XXXXXXXX, _XXXXXXX, XXXXXX_X, X____XXX, XXXXXXXX,
  XXXXXXXX, XXX__XXX, XXXXXXXX, XXXXXXXX, __X_XXXX, XXXXX_XX, ____XXXX, XXXXXXXX,
  XXXXXXXX, XXX__XXX, XXXXXXXX, XXXXXXXX, _____XXX, XXXXXXX_, ____XXXX, XXXXXXXX,
  XXXXXXXX, XXXX_XXX, XXXXXXXX, XXXXXXXX, X___XXXX, XXXXXX_X, XX__XXXX, XXXXXXXX,
  XXXXXXXX, XXXXX_XX, XXXXXXXX, XXXXXXXX, X____XXX, XXXXXXXX, X__XXXXX, XXXXXXXX,
  XXXXXXXX, XXXX__XX, XXXXXXXX, XXXXXXXX, X____XXX, XXXXXXXX, X__XXXXX, XXXXXXXX,
  XXXXXXXX, XXXX__XX, XXXXXXXX, XXXXXXXX, XXXX__XX, XXXXXXXX, X__XXXXX, XXXXXXXX,
  XXXXXXXX, XXXX_X_X, XXXXXXXX, XXXXXXXX, X__X__XX, XXXXXXXX, X__XXXXX, XXXXXXXX,
  XXXXXXXX, XXXX_X__, XXXXXXXX, XX__XX_X, X__X__XX, XXXXX_XX, ___XXXXX, XXXXXXXX,
  XXXXXXXX, XXXX__X_, XXXXXXXX, XXXXXXX_, _____XXX, XXXXXXXX, ___XXXXX, XXXXXXXX,
  XXXXXXXX, XXXXX_X_, _XXXXXXX, XXXXXXXX, X__XXXXX, XXXXXXX_, __XXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXX_, _X_XXXXX, XXXXXXXX, X_XXXXXX, XXXXXXX_, __XXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, __XXXXXX, XXXXXXXX, X_XXXXXX, XXXXXX__, _XXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, __XXXXXX, XXXXXXXX, X_XXXXXX, XXXXX___, _XXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, __XXXXXX, XXXXX_X_, _XXXXXXX, X_XXX__X, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, __XXXXXX, ________, ______XX, XXX____X, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, X__XXXX_, XX______, ______XX, XXXXX_XX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XX_XXXXX, XXX_____, ___X_XXX, XXXX__XX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XX__XXXX, XXXXX___, __XXXXXX, XXXX_XXX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, X____XXX, XXXXXXXX, XXXXXXXX, XXX___XX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XX___X_X, XXXXXXXX, XXXXXXXX, XX____XX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XX_____X, _XXXXXXX, XXXXXXXX, XX____XX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XX______, _XXXXXXX, XXXXXXXX, X_____XX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XX______, X_XXXXXX, XXXXXXXX, ______XX, XXXXXXX_, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, XX_XXXX_, XXXXXXXX, XXXXXXXX, XXXX__XX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, X__XXXXX, XXXXXXXX, XXXXXXXX, XXXXX_XX, XXXXXXXX, XXXXXXXX,
  XXXXXXXX, XXXXXXXX, __XXXXXX, XXXXXXXX, XXXXXXXX, XXXXX__X, XXXXXXXX, XXXXXXXX
};

GUI_CONST_STORAGE GUI_BITMAP bmlch = {
  64, // xSize
  64, // ySize
  8, // BytesPerLine
  1, // BitsPerPixel
  _aclch,  // Pointer to picture data (indices)
  &_Pallch   // Pointer to palette
};

/*************************** End of file ****************************/
